{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backstage
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
