apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  postgres-admin-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  backend-secret: {{ .Values.secrets.backendSecret | b64enc | quote }}
{{- if .Values.secrets.github.token }}
  github-token: {{ .Values.secrets.github.token | b64enc | quote }}
{{- end }}
# Note: pat-secret should be manually added to the secret if using Azure DevOps
