apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.backstage.backend.service.type }}
  ports:
    - port: {{ .Values.backstage.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/instance: {{ .Release.Name }}
