apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: <YOUR-USERNAME-HERE>
  annotations:
    graph.microsoft.com/user-id: <YOUR-ENTRA-OBJECT-ID-HERE>
spec:
  profile:
    displayName: <YOUR-NAME-HERE>
    email: <YOUR-EMAIL-HERE>
  memberOf:
    - guests
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: <YOUR-USERNAME-HERE>
  annotations:
    graph.microsoft.com/user-id: <YOUR-ENTRA-OBJECT-ID-HERE>
spec:
  profile:
    displayName: <YOUR-NAME-HERE>
    email: <YOUR-EMAIL-HERE>
  memberOf:
    - guests
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
